export const CREATE_TASK_START = 'CREATE_TASK_START';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';

export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';

export const ADD_TASKS_START = 'ADD_TASKS_START';
export const ADD_TASKS_SUCCESS = 'ADD_TASKS_SUCCESS';
export const ADD_TASKS_ERROR = 'ADD_TASKS_ERROR';
